[package]
name = "Information_Transformation_Algorithms_Task05"
version = "0.1.0"
edition = "2024"

[dependencies]
burrows_wheeler_transform = {path = "burrows_wheeler_transform"}
move_to_front = {path = "move_to_front"}